// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdDqLlXGn2RXOgnfPJ8ZMjkQ1DWUD7SMM',
    appId: '1:755773183987:web:51b546d91f6b8bd793e486',
    messagingSenderId: '755773183987',
    projectId: 'egrocer-457a9',
    authDomain: 'egrocer-457a9.firebaseapp.com',
    storageBucket: 'egrocer-457a9.appspot.com',
    measurementId: 'G-VR8YQ6BZ9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv0dHtM5Qhdlywws5WLW-Wc-fN8K2iSkE',
    appId: '1:755773183987:android:41f2f290562804ec93e486',
    messagingSenderId: '755773183987',
    projectId: 'egrocer-457a9',
    storageBucket: 'egrocer-457a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Bo2AY6yqfCbJKvLYybAKIjHCLSFS6e8',
    appId: '1:755773183987:ios:19c271e5de5acc1093e486',
    messagingSenderId: '755773183987',
    projectId: 'egrocer-457a9',
    storageBucket: 'egrocer-457a9.appspot.com',
    androidClientId:
        '755773183987-42d5161052q353fslbqssggfstbt0dqp.apps.googleusercontent.com',
    iosClientId:
        '755773183987-n01f1cfkr8o40cdjk0meod40kbevm2t1.apps.googleusercontent.com',
    iosBundleId: 'com.wrteam.egrocer.seller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Bo2AY6yqfCbJKvLYybAKIjHCLSFS6e8',
    appId: '1:755773183987:ios:19c271e5de5acc1093e486',
    messagingSenderId: '755773183987',
    projectId: 'egrocer-457a9',
    storageBucket: 'egrocer-457a9.appspot.com',
    androidClientId:
        '755773183987-42d5161052q353fslbqssggfstbt0dqp.apps.googleusercontent.com',
    iosClientId:
        '755773183987-n01f1cfkr8o40cdjk0meod40kbevm2t1.apps.googleusercontent.com',
    iosBundleId: 'com.wrteam.egrocer.seller',
  );
}
